#pragma once

enum IMAGE_FORMAT
{
    IMAGE_FORMAT_RGBA8BIT,
    IMAGE_FORMAT_BGRA8BIT,
    IMAGE_FORMAT_RGBA16BIT,
    IMAGE_FORMAT_BGRA16BIT,
    IMAGE_FORMAT_RGB30 
};

enum BUFFER_FORMAT 
{ 
    BUFFER_FORMAT_RGBA32, 
    BUFFER_FORMAT_RGBA64, 
    BUFFER_FORMAT_YUY2,
    BUFFER_FORMAT_Y216 
};